### ISSUE TITLE
Adding Sendgrid Category

### ISSUE THREAD

**Issue by lancasterjones** [yukoff/magento2-sendgrid-smtp#1]
Hi,

It would be great to add a category for Sendgrid Stats. It should be as simple as adding "category":"custom category" to the header. 
I'm not very familiar with Magento and couldn't do it.
I only want to add 1 category, and it could be hardcoded, it wouldn't need to be assigned in the Magento admin. Could you provide info on which file should be modified?

**Comment by yukoff** [comment]
Hi, @lancasterjones 

Could you please elaborate a bit? Do you mean a dropdown list for categories or a simple text input? I haven't worked with SendGrid Stats, so I might need to get the basic idea (few words would be a help).

**Comment by lancasterjones** [comment]
Sure:

Sendgrid allows you to add one or several categories to outgoing emails,
they work pretty much like labels.
They come in handy when analyzing what store the emails are being sent
from. In my case, I use one SendGrid account for several website. Without
the labels I can't analyze the email statistics by website.
One category in a simple text input would be enough.
Does this help clarify?

Alejandro Lancaster
vende.io
(0133) 1306 4356

**Comment by yukoff** [comment]
Sure, @lancasterjones, thank you. I also checked the documentation - seems you referring to https://sendgrid.com/docs/API_Reference/SMTP_API/categories.html

I added simple implementation as requested, however it seems it could be improved according to
https://sendgrid.com/docs/API_Reference/Web_API/Statistics/index.html#-Category-List - however currently I have issues authenticating in SendGrid under my current heroku setup, so I left this for later.

**Comment by lancasterjones** [comment]
I have tested it and can now confirm that it works exactly as it should. The category is being assigned to each email and statistics can now be filtered by category.
Thank you for taking your time and developing this.
I would recommend making this available in the Magento Marketplace as it is very useful.
