### ISSUE TITLE
Publish on packagist and create a release

### ISSUE THREAD

**Issue by paales** [yukoff/magento2-sendgrid-smtp#2]
Hi there,

It would be nice if we wouldn't have to add a vcs to the composer.json file (makes installation slow).

**Comment by yukoff** [comment]
Hi @paales 

Well, initially it was created as a quick'n'dirty piece of code to cover basic needs of mine ;) so I didn't ever thought about that packagist thing. :) On the other hand it makes sense - I'll get back on this soon.

**Comment by paales** [comment]
@yukoff If you believe the package isn't ready to be used it shouldn't be on packagist as you mentioned. Just thought it might be a good idea if it is production ready.

**Comment by yukoff** [comment]
Hi @paales, thanks for your feedback. Actually I think there's nothing special in code, so I've created packagist package as requested. Will update README soon.

**Comment by yukoff** [comment]
Updated README as well. Closing.
