### ISSUE TITLE
Pemission Denied

### ISSUE THREAD

**Issue by lokranjan** [yukoff/magento2-sendgrid-smtp#3]
Hi,
Please help.
I am getting permission denied issue in magento 2 sendgrid.

http://awesomescreenshot.com/0ce63wk571

Thanks
Lokranjan

**Comment by yukoff** [comment]
Hi,
Sorry for delay - it seems everything is correct except username, AFAIK for sendgrid it used to be email address used for register (or is it additional credentials created afterwards?). Also, I don't use categories at the moment, so I can't say for sure should they exist prior to use them - could you try without specifying category first?

As you mentioned [here](https://github.com/yukoff/magento2-sendgrid-smtp/commit/6069f174c380c9f5af1c8fe75b076e41aea3fb74#commitcomment-18774075) when you use curl it works, but most likely you are using their web-api, not smtp - just to clarify, are you using the same credentials?

**Comment by yukoff** [comment]
Ah, forgot the second part from the commit comment - :NONE shouldn't be used, but the error is odd and seems it's from the magento itself (it uses a bit modified Zend framework v1), I'll try to investigate this deeper and probably file a report to magento team.

**Comment by yukoff** [comment]
Hi @lokranjan, have you managed to make this work for you? Could I close this?
